name: macOS Build Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: wolfssl/wolfssl
        path: wolfssl
    - name: brew
      run: brew install automake libtool
    - name: wolfssl autogen
      working-directory: ./wolfssl
      run: ./autogen.sh
    - name: wolfssl configure
      working-directory: ./wolfssl
      run: ./configure
    - name: wolfssl make
      working-directory: ./wolfssl
      run: make
    - name: wolfssl make install
      working-directory: ./wolfssl
      run: make install

    - uses: actions/checkout@v3
      with:
        repository: wolfssl/wolfssl
        path: wolfssl

    - uses: actions/checkout@master
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
